### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by fatenazzez** [ssozuer/lsas#3]
Why are my contributions not showing up on my profile???

**Comment by fatenazzez** [comment]
Why are my contributions not showing up on my profile???

**Comment by OnurIltan** [comment]
https://help.github.com/articles/i-don-t-see-myself-in-the-repository-contributors-graph/

Check this link for the problem.

**Comment by bugrataskaya** [comment]
it would be helpful too :
http://stackoverflow.com/questions/15289768/github-commits-arent-recorded-in-the-your-contributions-calendar
