### ISSUE TITLE
 WARN org.apache.jasper.compiler.TagLibraryInfoImpl - Unknown element (deferred-value) in attribute

### ISSUE THREAD

**Issue by ssozuer** [ssozuer/lsas#5]
Guys, server outputs this warning. I don't know if it is something important. But we should investigate it.

**Comment by OnurIltan** [comment]
https://javaage.wordpress.com/2013/05/03/jstl1-2-unknown-elementdeferred-value-error-in-tomcat-log/

These instructions can solve the problem.

**Comment by ssozuer** [comment]
modified pom.xml so issue is solved.
